### ISSUE TITLE
Issues running follow_gh.py

### ISSUE THREAD

**Issue by archcorsair** [cassac/bulk_follow#1]
Expected: Follow all users in my csv
Got: This error
`Traceback (most recent call last):
  File "follow_gh.py", line 2, in <module>
    from selenium import webdriver
ImportError: No module named selenium`

Any info on this would be great! Chrome is installed the default standard way.

**Comment by cassac** [comment]
These scripts rely on the Selenium web-driver to execute. Running `pip install -r requirements.txt` in your terminal from the repo's root directory should install the dependency or just run `pip install selenium`. If you have Python 3 installed you will need to run `python3 follow_gh.py` instead of `python follow_gh.py`. Does that resolve the issue? What OS are you using?

**Comment by archcorsair** [comment]
**OS:** MacOS Sierra 10.12.1
**Python Version:** 3.5.2
I manually installed selenium using `pip install selenium`
Upon successful installation: `Successfully installed selenium-3.0.1`

Still get the same error when I run: `python3 follow_gh.py`

**Comment by cassac** [comment]
I'm suspicious that selenium is being installed for the wrong version of Python. You can install it for Python3 via `pip3 install selenium` or possibly try running it with Python2 via `python2 follow_gh.py`.

**Comment by archcorsair** [comment]
You were right! I ran it using python v2.x and it looks to be running now. Will let you know if I run into any other bumps. Appreciate the help 👍

**Comment by archcorsair** [comment]
Ran successfully without a hitch.
